### ISSUE TITLE
Full Stack Capstone Project

### ISSUE THREAD

**Issue by ezraermy** [ezraermy/Full-Stack-Capstone-Backend#22]
#### For this project, our team consists of three members:
@ezraermy,   
@yosaddis ,  
@PabloEGonz 

#### Tasks assigned to each member
@PabloEGonz will be working on the User part
@yosaddis will be working on the Car part
@ezraermy will be working on the Reservation part
- Each one of us has in total 28pts

#### Screenshots for the Kanban board
- page 1
![Kanaban pg 1](https://github.com/ezraermy/Full-Stack-Capstone-Backend/assets/35451409/323477f6-4b09-4aa7-a4fa-32e5f08e05e3)
- page 2
![Kanaban pg 2](https://github.com/ezraermy/Full-Stack-Capstone-Backend/assets/35451409/ac86dc95-e35a-4b70-b082-5b6368137215)

**Comment by Meltrust** [comment]
Hi @ezraermy 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not contain a screenshot of the kanban board.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Meltrust** [comment]
Hi @ezraermy,

## Wow, you did it 🎉 
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### To highlight

- All cards have assignees, and descriptions and have been pointed.  The pointings meet the associated requirements.✔️ 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
